# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcms" do
  version "0.1.0-beta.4"

  on_macos do
    on_arm do
      sha256 "5764de2e1ed6e99e5fa073a7fe397044bcb66e12eb9dbd2e7af40d082b2ef364"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "be7c91edc004555f313a0f97016e0c4597a7324596c45f06c691e1c54079a897"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20fffe42454da90593be54c113fa8ae7feb83aab6b85d1cf168fb928e5ea3983"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8be43b68051f8fc28a3dda014c08db4ce6aeba67b7a7e44edb32a3db047b0c0b"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_amd64.tar.gz"
    end
  end

  name "dcms"
  desc "Schema-first content engine: a validated REST backend from a YAML schema, no code."
  homepage "https://github.com/blazing-Gael/dcms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcms"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dcms"]
    end
  end

  # No zap stanza required
end
