# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcms" do
  version "0.1.0-beta.3"

  on_macos do
    on_arm do
      sha256 "846a7b7e0bc26e128c9bcafd81386fbdda07d589b5882eceec8f86c4902ce956"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f9147f4ca3e725fe71b39cc66fa3379420f8ebd53cea3f04097e9aa9371e179"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2818ac843a31970ac5afca3c63b52fd1313228cb627d6d10a8fff3e0b1364541"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4942e63f8d264d2e14ab8a6b60ec482bfe5afb0fa5e695999a9516c4c69e9723"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_amd64.tar.gz"
    end
  end

  name "dcms"
  desc "Schema-first content engine: a validated REST backend from a YAML schema, no code."
  homepage "https://github.com/blazing-Gael/dcms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcms"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dcms"]
    end
  end

  # No zap stanza required
end
