# This file was generated by GoReleaser. DO NOT EDIT.
cask "dcms" do
  version "0.1.0-beta.2"

  on_macos do
    on_arm do
      sha256 "1ea1df4f449950a591b8e2b7cc17d613afe5fab43864ab3955b3cf1254db4687"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "76d3e219733c00ec437879d2fdcc34d2be8a64caf0f80385a399462e4ec2622c"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ad4d3b1d1f75268b69495826568651d43bd2d384dca5a0ad1980c35ea878a146"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4e6faca424d2586bcefafacffd8787c5aa82887b905eda6c2f2b7a8d120524a7"
      url "https://github.com/blazing-Gael/dcms/releases/download/v#{version}/dcms_linux_amd64.tar.gz"
    end
  end

  name "dcms"
  desc "Schema-first content engine: a validated REST backend from a YAML schema, no code."
  homepage "https://github.com/blazing-Gael/dcms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dcms"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dcms"]
    end
  end

  # No zap stanza required
end
